# used in dbt test 

version: 2

models:
  - name: stg_divolte_clickstream
    columns:
      - name: firstInSession
        tests:
          - accepted_values:
              values: [True, False]
    columns:
      - name: detectedDuplicate
        tests:
          - accepted_values:
              values: [True, False]
    columns:
      - name: detectedCorruption
        tests:
          - accepted_values:
              values: [True, False]
    columns:
      - name: firstInSession
        tests:
          - accepted_values:
              values: [True, False]
    columns:
      - name: timestamp
        tests:
          - not_null
