version: 2

models:
  - name: dm_daily_visits
    description: This datamart contains agregated daily statistics about pages visits

    columns:
      - name: partyID
        description: identifies a device from which a page was opened
 
      - name: remotehost
        description: identifies an IP address from which a page was opened
 
      - name: sessionid
        description: identifies an session during which a page was opened
 
      - name: daily_opens
        description: number of opens of a page during a day by a party from a host during a session 

      - name: mean_screen_Pixel_Height
        description: mean screen height from a party during in a session in a day 

      - name: mean_screen_Pixel_Width
        description: mean screen width from a party during in a session in a day 
